version: "3.7"
services:
  postgres:
    image: postgres:12
    container_name: postgres-for-prisma-issue
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
